import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Head from "next/head"; 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"> 
      <body>
      <Navbar />
        {children}
      <Footer />
        </body>
    </html>
  );
}
